### ISSUE TITLE
CMake should fail if bad DEFAULT value specified

### ISSUE THREAD

**Issue by connorimes** [energymon/energymon#14]
If a bad DEFAULT value is specified, CMake should fail with a helpful error message.  It should ensure that a valid value is given for the platform being compiled for as well (e.g. it should fail if `rapl` is specified when running in Windows or on an Apple system).  Currently it just doesn't produce the `energymon-default` and `energymon-default-static` targets.  Running `make` then fails because it can't link against `energymon-default`:

<pre>
Scanning dependencies of target energymon
[  3%] Building C object CMakeFiles/energymon.dir/src/app/energymon.c.o
Linking C executable bin/energymon
/usr/bin/ld: cannot find -lenergymon-default
collect2: error: ld returned 1 exit status
CMakeFiles/energymon.dir/build.make:85: recipe for target 'bin/energymon' failed
make[2]: *** [bin/energymon] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/energymon.dir/all' failed
make[1]: *** [CMakeFiles/energymon.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by jonathan-alvaro** [comment]
My problem might be related to this issue so I'll post it here. When I ran CMake with the `ENERGYMON_BUILD_DEFAULT` set to rapl and `ENERGYMON_BUILD_LIB` set to NONE, the compiled library only compiles the energymon-default. But, this is a problem as for some reason the default energymon-default does not work and always gives 0 on every read. Then, I recompiled energymon with `ENERGYMON_BUILD_LIB` set to rapl. This time, I modified the line in my program to use `energymon_get_rapl` instead of `energymon_get_default` which works perfectly.

**Comment by connorimes** [comment]
Hi @jonathan-alvaro - I'm not able to reproduce your problem.  If I configure cmake with `cmake .. -DENERGYMON_BUILD_DEFAULT=rapl -DENERGYMON_BUILD_LIB=NONE` it correctly builds the rapl implementation as the `energymon-default` library and I am able to read, e.g., using the `energymon-info` utility.

Everything you described sounds like correct behavior except that you were getting 0 values on read.  If you're writing your own code that links against energymon-default, you will have to rebuild it if you're using static libraries (which is CMake's default, as opposed to using shared object libraries).  So if you statically linked against a dummy default implementation previously but didn't recompile, you would continue to get 0 values since it's still using the dummy implementation.  For debug purposes, you can use the `energymon.fsource` function pointer to get the human-readable description of the library you're linked against and print out the string.

**Comment by jonathan-alvaro** [comment]
To clarify, the 0 values on read happens only with code that I wrote on my own. The readings from `energymon-info` works just fine. The weird thing is that the same program that I run worked on another system that runs on ubuntu 18.04. But, when I moved to another system with Ubuntu 14.04, it suddenly gives out 0 reads.

**Comment by connorimes** [comment]
Ubuntu 14.04 is old enough that it may not include (or load) the `intel_rapl` kernel module by default, which energmyon-rapl requires.  Please verify that 1) the `intel_rapl` kernel module is loaded (`lsmod | grep intel_rapl`), and 2) that there are actually files at `/sys/class/powercap/` (e.g., `ls /sys/class/powercap/intel-rapl\:0/`).

**Comment by jonathan-alvaro** [comment]
1. I do have the `intel_rapl` module loaded to the kernel
2. Yes, there are files within the powercap intel-rapl folders.

**Comment by connorimes** [comment]
Thanks for the update.  That is strange behavior that I cannot explain.  The API design is to return 0 on read error and set `errno`, so in your code, if you ever a get a 0 return value from `fread`, you should check if errno is set and respond appropriately (e.g., by logging the error).  (You should also check that `finit` is returning successfully first.)  Hopefully that will give us some idea of what's going on.  It's still possible that errno won't be set, e.g., if the `energy_uj` file is actually returning a 0 value.  Since I cannot reproduce this issue, you may just need to run it through gdb (or other debugger) yourself.

If you do see a problem with the library, can I request that you please open a new issue? I'm going to (finally) fix this original issue in `CMakeLists.txt`.

**Comment by connorimes** [comment]
@jonathan-alvaro I just wanted to follow up to see if you're still having trouble.  You can definitely open a new issue if there is indeed a problem.  Cheers.
