### ISSUE TITLE
ipg: PG_Shutdown causes errors in readers getting samples from PMU

### ISSUE THREAD

**Issue by cimes-isi** [energymon/energymon#51]
This issue is for documentation purposes, since it's not really a bug in `energymon-ipg`.

The `ipg` implementation experiences issues when multiple instances---or other software tools, including Intel Power Gadget itself---share the PowerGadgetLib backend.  Calling the shutdown method in any one instance causes errors on other readers:
```
ERROR: EnergyDriver_executeCommands [via readSample] returned 0xe00002bc
```

Example: Start Intel Power Gadget, run software using PowerGadgetLib w/out `usePMU=false`, stop this software (`PG_Shutdown`), then IPG starts failing to collect data.

I asked about the issue on Intel's forums some time ago, but didn't receive a reply [1].

[1] https://community.intel.com/t5/Software-Tuning-Performance/Power-Gadget-PG-Shutdown-when-UsePMU-false-still-affects-SW/m-p/1341318

**Comment by connorimes** [comment]
From https://www.intel.com/content/www/us/en/developer/articles/tool/power-gadget.html:

> As of October 9, 2023, no functional, security, or other updates will be provided for Intel® Power Gadget. Intel® Power Gadget will no longer be available after October 13, 2023. All versions are provided as is. Intel recommends that users of Intel® Power Gadget uninstall and discontinue use as soon as possible and use Intel® Performance Counter Monitor (Intel® PCM),  an application programming interface (API) and a set of tools based on the API to monitor performance and energy metrics of Intel® Core™, Xeon®, Atom® and Xeon® Phi™ processors. PCM works on Linux, Windows, Mac OS X, FreeBSD, DragonFlyBSD and ChromeOS operating systems.

Closing since clearly this issue won't be fixed in IPG.
