### ISSUE TITLE
microjoules value: 0 from API 

### ISSUE THREAD

**Issue by edisonchan** [energymon/energymon#52]
My code(profile_stress.c):

```
#include <stdio.h>
#include <stdlib.h>
#include "energymon.h"

int main(void)
{
	energymon em;
	uint64_t start_uj, end_uj;

	

	energymon_get_default(&em);
	em.finit(&em);

	// profile application function
	start_uj = em.fread(&em);
        system("stress -c 1 -t 10");
	end_uj = em.fread(&em);

	printf("Total energy for stress -c 1 -t 10 in microjoules: %"PRIu64"\n", end_uj - start_uj);

	// destroy the instance
	em.ffinish(&em);

	return 0;
}

```

The Makefile:
```
CFLAGS += $(shell pkg-config --cflags energymon-default)
LDFLAGS += $(shell pkg-config --libs --static energymon-default)

profile_stress: profile_stress.c
	$(CC) $(CFLAGS) profile_stress.c -o $@ $(LDFLAGS)

```

run step:
```
make
sudo ./profile_stress
```
stress: info: [1491] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [1491] successful run completed in 10s
Total energy for stress -c 1 -t 10 in microjoules: 0

but if run via energy-rapl-cmd-profile:
`sudo energymon-rapl-cmd-profile stress -c 1 -t 10`
Executing: stress -c 1 -t 10
stress: info: [1555] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
stress: info: [1555] successful run completed in 10s
Time (ns): 10004833886
Energy (uJ): 640470528
Power (W): 64.016108

My system:
Ubutnu 22.04
CPU: Intel W7-2495X
Linux u22 6.4.11-060411-generic #202308161732 SMP PREEMPT_DYNAMIC Wed Aug 16 17:41:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

How can I fix this problem?

**Comment by connorimes** [comment]
You're code is using `energymon_get_default` which is for the `energymon-default` library, not `energymon-rapl`.  The `default` library is intended to be replaced with whatever implementation a user desires so they don't have to modify their code on different platforms.  However if you don't specify `-DENERGYMON_BUILD_DEFAULT=<implementation>` with the `cmake` command when building energymon, it compiles the `dummy` implementation, which always returns 0 for the `fread` function.  If you were to add some lines to print out the human-readable energymon source, you'd probably see that it's using the `default` implementation, e.g.:

```C
char buf[256] = { 0 };
em.fsource(buf, sizeof(buf));
printf("source: %s\n", buf);
```

You could also just run:
```sh
energymon-info
```
to check what your `default` implementation currently is.

I also see that you're including `energymon.h` but not `energymon-default.h` -- you're probably seeing a compiler warning about the `energymon_get_default` function.

**Comment by edisonchan** [comment]
> You're code is using `energymon_get_default` which is for the `energymon-default` library, not `energymon-rapl`. The `default` library is intended to be replaced with whatever implementation a user desires so they don't have to modify their code on different platforms. However if you don't specify `-DENERGYMON_BUILD_DEFAULT=<implementation>` with the `cmake` command when building energymon, it compiles the `dummy` implementation, which always returns 0 for the `fread` function. If you were to add some lines to print out the human-readable energymon source, you'd probably see that it's using the `default` implementation, e.g.:
> 
> ```c
> char buf[256] = { 0 };
> em.fsource(buf, sizeof(buf));
> printf("source: %s\n", buf);
> ```
> 
> You could also just run:
> 
> ```shell
> energymon-info
> ```
> 
> to check what your `default` implementation currently is.
> 
> I also see that you're including `energymon.h` but not `energymon-default.h` -- you're probably seeing a compiler warning about the `energymon_get_default` function.

Thanks for your replay.
The energy value works after use ```cmake .. -DENERGYMON_BUILD_LIB=rapl -DENERGYMON_BUILD_DEFAULT=rapl -DCMAKE_BUILD_TYPE=Release``` to build energymon.
